<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <LangVersion>14</LangVersion>
    <NoWarn Condition="$(MSBuildProjectName.EndsWith('Tests'))">$(NoWarn);CA1707</NoWarn>
    <TestingPlatformDotnetTestSupport Condition="$(MSBuildProjectName.EndsWith('Tests'))">true</TestingPlatformDotnetTestSupport>
    <UseMicrosoftTestingPlatformRunner Condition="$(MSBuildProjectName.EndsWith('Tests'))">true</UseMicrosoftTestingPlatformRunner>
    <OutputType Condition="$(MSBuildProjectName.EndsWith('Tests'))">Exe</OutputType>
  </PropertyGroup>
</Project>
