// <auto-generated />
using System;
using Cemetery.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cemetery.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CemeteryDbContext))]
    [Migration("20261005093134_Register")]
    partial class Register
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cemetery")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cemetery.Domain.Identity.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_invitations");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("invitations_token_hash_key");

                    b.ToTable("invitations", "cemetery");
                });

            modelBuilder.Entity("Cemetery.Domain.Identity.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_memberships");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("memberships_tenant_user_key");

                    b.ToTable("memberships", "cemetery");
                });

            modelBuilder.Entity("Cemetery.Domain.Identity.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("organizations_slug_key");

                    b.ToTable("organizations", "cemetery");
                });

            modelBuilder.Entity("Cemetery.Domain.Layout.Cemetery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Polygon>("PlanBounds")
                        .HasColumnType("geometry(Polygon,4326)")
                        .HasColumnName("plan_bounds");

                    b.Property<string>("PlanImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("plan_image_url");

                    b.Property<int>("RestPeriodYears")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(15)
                        .HasColumnName("rest_period_years");

                    b.Property<bool>("Schematic")
                        .HasColumnType("boolean")
                        .HasColumnName("schematic");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_cemeteries");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_cemeteries_tenant_id_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_cemeteries_tenant_id");

                    b.ToTable("cemeteries", "cemetery");
                });

            modelBuilder.Entity("Cemetery.Domain.Layout.GraveRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("label");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("section_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_grave_rows");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_grave_rows_tenant_id_id");

                    b.HasIndex("TenantId", "SectionId", "Label")
                        .IsUnique()
                        .HasDatabaseName("grave_rows_tenant_label_key");

                    b.ToTable("grave_rows", "cemetery");
                });

            modelBuilder.Entity("Cemetery.Domain.Layout.GraveSite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<Guid>("CemeteryId")
                        .HasColumnType("uuid")
                        .HasColumnName("cemetery_id");

                    b.Property<bool>("Closed")
                        .HasColumnType("boolean")
                        .HasColumnName("closed");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<Polygon>("Outline")
                        .HasColumnType("geometry(Polygon,4326)")
                        .HasColumnName("outline");

                    b.Property<Guid?>("RowId")
                        .HasColumnType("uuid")
                        .HasColumnName("row_id");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("section_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_grave_sites");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_grave_sites_tenant_id_id");

                    b.HasIndex("Outline")
                        .HasDatabaseName("ix_grave_sites_outline");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Outline"), "gist");

                    b.HasIndex("TenantId", "RowId")
                        .HasDatabaseName("ix_grave_sites_tenant_id_row_id");

                    b.HasIndex("TenantId", "SectionId")
                        .HasDatabaseName("ix_grave_sites_tenant_id_section_id");

                    b.HasIndex("TenantId", "CemeteryId", "Code")
                        .IsUnique()
                        .HasDatabaseName("grave_sites_tenant_code_key");

                    b.ToTable("grave_sites", "cemetery");
                });

            modelBuilder.Entity("Cemetery.Domain.Layout.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CemeteryId")
                        .HasColumnType("uuid")
                        .HasColumnName("cemetery_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<Polygon>("Outline")
                        .HasColumnType("geometry(Polygon,4326)")
                        .HasColumnName("outline");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_sections");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_sections_tenant_id_id");

                    b.HasIndex("TenantId", "CemeteryId", "Code")
                        .IsUnique()
                        .HasDatabaseName("sections_tenant_code_key");

                    b.ToTable("sections", "cemetery");
                });

            modelBuilder.Entity("Cemetery.Domain.Register.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_entries");

                    b.HasIndex("TenantId", "SubjectId")
                        .HasDatabaseName("ix_audit_entries_tenant_id_subject_id");

                    b.ToTable("audit_entries", "cemetery");
                });

            modelBuilder.Entity("Cemetery.Domain.Register.Deceased", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("BornOn")
                        .HasColumnType("date")
                        .HasColumnName("born_on");

                    b.Property<Guid>("CemeteryId")
                        .HasColumnType("uuid")
                        .HasColumnName("cemetery_id");

                    b.Property<DateOnly?>("DiedOn")
                        .HasColumnType("date")
                        .HasColumnName("died_on");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("family_name");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("given_name");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_deceased");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_deceased_tenant_id_id");

                    b.HasIndex("TenantId", "CemeteryId")
                        .HasDatabaseName("ix_deceased_tenant_id_cemetery_id");

                    b.ToTable("deceased", "cemetery");
                });

            modelBuilder.Entity("Cemetery.Domain.Register.DeceasedRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<DateOnly?>("BornOn")
                        .HasColumnType("date")
                        .HasColumnName("born_on");

                    b.Property<Guid>("DeceasedId")
                        .HasColumnType("uuid")
                        .HasColumnName("deceased_id");

                    b.Property<DateOnly?>("DiedOn")
                        .HasColumnType("date")
                        .HasColumnName("died_on");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("family_name");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("given_name");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_deceased_revisions");

                    b.HasIndex("TenantId", "DeceasedId", "Version")
                        .IsUnique()
                        .HasDatabaseName("deceased_revisions_version_key");

                    b.ToTable("deceased_revisions", "cemetery");
                });

            modelBuilder.Entity("Cemetery.Domain.Register.Interment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("BuriedOn")
                        .HasColumnType("date")
                        .HasColumnName("buried_on");

                    b.Property<Guid>("CemeteryId")
                        .HasColumnType("uuid")
                        .HasColumnName("cemetery_id");

                    b.Property<Guid>("DeceasedId")
                        .HasColumnType("uuid")
                        .HasColumnName("deceased_id");

                    b.Property<DateOnly?>("ExhumedOn")
                        .HasColumnType("date")
                        .HasColumnName("exhumed_on");

                    b.Property<Guid>("GraveSiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("grave_site_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<DateOnly?>("SupersededOn")
                        .HasColumnType("date")
                        .HasColumnName("superseded_on");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateOnly?>("TransferredOn")
                        .HasColumnType("date")
                        .HasColumnName("transferred_on");

                    b.HasKey("Id")
                        .HasName("pk_interments");

                    b.HasIndex("TenantId", "CemeteryId")
                        .HasDatabaseName("ix_interments_tenant_id_cemetery_id");

                    b.HasIndex("TenantId", "DeceasedId")
                        .IsUnique()
                        .HasDatabaseName("interments_open_deceased_key")
                        .HasFilter("exhumed_on IS NULL AND transferred_on IS NULL AND superseded_on IS NULL");

                    b.HasIndex("TenantId", "GraveSiteId", "Position")
                        .IsUnique()
                        .HasDatabaseName("interments_open_position_key")
                        .HasFilter("exhumed_on IS NULL AND transferred_on IS NULL AND superseded_on IS NULL");

                    b.ToTable("interments", "cemetery");
                });

            modelBuilder.Entity("Cemetery.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", "cemetery");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", "cemetery");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", "cemetery");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", "cemetery");
                });

            modelBuilder.Entity("Cemetery.Domain.Layout.GraveRow", b =>
                {
                    b.HasOne("Cemetery.Domain.Layout.Section", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "SectionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grave_rows_sections_tenant_id_section_id");
                });

            modelBuilder.Entity("Cemetery.Domain.Layout.GraveSite", b =>
                {
                    b.HasOne("Cemetery.Domain.Layout.Cemetery", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CemeteryId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grave_sites_cemeteries_tenant_id_cemetery_id");

                    b.HasOne("Cemetery.Domain.Layout.GraveRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RowId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_grave_sites_grave_rows_tenant_id_row_id");

                    b.HasOne("Cemetery.Domain.Layout.Section", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "SectionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grave_sites_sections_tenant_id_section_id");
                });

            modelBuilder.Entity("Cemetery.Domain.Layout.Section", b =>
                {
                    b.HasOne("Cemetery.Domain.Layout.Cemetery", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CemeteryId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sections_cemeteries_tenant_id_cemetery_id");
                });

            modelBuilder.Entity("Cemetery.Domain.Register.Deceased", b =>
                {
                    b.HasOne("Cemetery.Domain.Layout.Cemetery", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CemeteryId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deceased_cemeteries_tenant_id_cemetery_id");
                });

            modelBuilder.Entity("Cemetery.Domain.Register.DeceasedRevision", b =>
                {
                    b.HasOne("Cemetery.Domain.Register.Deceased", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "DeceasedId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deceased_revisions_deceased_tenant_id_deceased_id");
                });

            modelBuilder.Entity("Cemetery.Domain.Register.Interment", b =>
                {
                    b.HasOne("Cemetery.Domain.Layout.Cemetery", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CemeteryId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_interments_cemeteries_tenant_id_cemetery_id");

                    b.HasOne("Cemetery.Domain.Register.Deceased", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "DeceasedId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_interments_deceased_tenant_id_deceased_id");

                    b.HasOne("Cemetery.Domain.Layout.GraveSite", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "GraveSiteId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_interments_grave_sites_tenant_id_grave_site_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Cemetery.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Cemetery.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Cemetery.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
